//! Generated by Snowball 2.0.0 - https://snowballstem.org/

package ru

import (
	snowballRuntime "github.com/snowballstem/snowball/go"
)

var A_0 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u0432\u0448\u0438\u0441\u044C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0432\u0448\u0438\u0441\u044C", A: 0, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0432\u0448\u0438\u0441\u044C", A: 0, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0432", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0432", A: 3, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0432", A: 3, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0432\u0448\u0438", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0432\u0448\u0438", A: 6, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0432\u0448\u0438", A: 6, B: 2, F: nil},
}

var A_1 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u0435\u043C\u0443", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u043C\u0443", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0445", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0445", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u044E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044E\u044E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u044E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u044E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044F\u044F", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0430\u044F", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043C\u0438", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043C\u0438", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0439", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0439", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0439", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u0439", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0433\u043E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u0433\u043E", A: -1, B: 1, F: nil},
}

var A_2 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u0432\u0448", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0432\u0448", A: 0, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0432\u0448", A: 0, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0449", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044E\u0449", A: 3, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u044E\u0449", A: 4, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043D\u043D", A: -1, B: 1, F: nil},
}

var A_3 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u0441\u044C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0441\u044F", A: -1, B: 1, F: nil},
}

var A_4 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u044B\u0442", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u044E\u0442", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u044E\u0442", A: 1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u044F\u0442", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0442", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u0435\u0442", A: 4, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0442", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043D\u044B", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043D\u044B", A: 7, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0442\u044C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u0442\u044C", A: 9, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0442\u044C", A: 9, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0448\u044C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0448\u044C", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u044E", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u044E", A: 14, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043B\u0430", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043B\u0430", A: 16, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043B\u0430", A: 16, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043D\u0430", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043D\u0430", A: 19, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0442\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0442\u0435", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0439\u0442\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u0439\u0442\u0435", A: 23, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0439\u0442\u0435", A: 23, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043B\u0438", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043B\u0438", A: 26, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043B\u0438", A: 26, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0439", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0443\u0439", A: 29, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0439", A: 29, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043B", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043B", A: 32, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043B", A: 32, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043C", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043C", A: -1, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043D", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043D", A: 38, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043B\u043E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B\u043B\u043E", A: 40, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u043B\u043E", A: 40, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043D\u043E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043D\u043E", A: 43, B: 2, F: nil},
	&snowballRuntime.Among{Str: "\u043D\u043D\u043E", A: 43, B: 1, F: nil},
}

var A_5 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u0443", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044F\u0445", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u044F\u0445", A: 1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0430\u0445", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044B", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044E", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044C\u044E", A: 6, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u044E", A: 6, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044F", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044C\u044F", A: 9, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u044F", A: 9, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0430", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0432", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u0432", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044C\u0435", A: 15, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0435", A: 15, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0438", A: 18, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0438", A: 18, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044F\u043C\u0438", A: 18, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u044F\u043C\u0438", A: 21, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0430\u043C\u0438", A: 18, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0439", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0439", A: 24, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0435\u0439", A: 25, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0439", A: 24, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u0439", A: 24, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044F\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u044F\u043C", A: 29, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0430\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u0438\u0435\u043C", A: 32, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u043C", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E", A: -1, B: 1, F: nil},
}

var A_6 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u043E\u0441\u0442", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043E\u0441\u0442\u044C", A: -1, B: 1, F: nil},
}

var A_7 = []*snowballRuntime.Among{
	&snowballRuntime.Among{Str: "\u0435\u0439\u0448", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u044C", A: -1, B: 3, F: nil},
	&snowballRuntime.Among{Str: "\u0435\u0439\u0448\u0435", A: -1, B: 1, F: nil},
	&snowballRuntime.Among{Str: "\u043D", A: -1, B: 2, F: nil},
}

var G_v = []byte{33, 65, 8, 232}

type Context struct {
	i_p2 int
	i_pV int
}

func r_mark_regions(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	context.i_pV = env.Limit
	context.i_p2 = env.Limit
	var v_1 = env.Cursor
lab0:
	for {
	golab1:
		for {
		lab2:
			for {
				if !env.InGrouping(G_v, 1072, 1103) {
					break lab2
				}
				break golab1
			}
			if env.Cursor >= env.Limit {
				break lab0
			}
			env.NextChar()
		}
		context.i_pV = env.Cursor
	golab3:
		for {
		lab4:
			for {
				if !env.OutGrouping(G_v, 1072, 1103) {
					break lab4
				}
				break golab3
			}
			if env.Cursor >= env.Limit {
				break lab0
			}
			env.NextChar()
		}
	golab5:
		for {
		lab6:
			for {
				if !env.InGrouping(G_v, 1072, 1103) {
					break lab6
				}
				break golab5
			}
			if env.Cursor >= env.Limit {
				break lab0
			}
			env.NextChar()
		}
	golab7:
		for {
		lab8:
			for {
				if !env.OutGrouping(G_v, 1072, 1103) {
					break lab8
				}
				break golab7
			}
			if env.Cursor >= env.Limit {
				break lab0
			}
			env.NextChar()
		}
		context.i_p2 = env.Cursor
		break lab0
	}
	env.Cursor = v_1
	return true
}

func r_R2(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if !(context.i_p2 <= env.Cursor) {
		return false
	}
	return true
}

func r_perfective_gerund(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_0, context)
	if among_var == 0 {
		return false
	}
	env.Bra = env.Cursor
	if among_var == 1 {
	lab0:
		for {
			var v_1 = env.Limit - env.Cursor
		lab1:
			for {
				if !env.EqSB("\u0430") {
					break lab1
				}
				break lab0
			}
			env.Cursor = env.Limit - v_1
			if !env.EqSB("\u044F") {
				return false
			}
			break lab0
		}
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !env.SliceDel() {
			return false
		}
	}
	return true
}

func r_adjective(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_1, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_adjectival(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	if !r_adjective(env, context) {
		return false
	}
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		among_var = env.FindAmongB(A_2, context)
		if among_var == 0 {
			env.Cursor = env.Limit - v_1
			break lab0
		}
		env.Bra = env.Cursor
		if among_var == 1 {
		lab1:
			for {
				var v_2 = env.Limit - env.Cursor
			lab2:
				for {
					if !env.EqSB("\u0430") {
						break lab2
					}
					break lab1
				}
				env.Cursor = env.Limit - v_2
				if !env.EqSB("\u044F") {
					env.Cursor = env.Limit - v_1
					break lab0
				}
				break lab1
			}
			if !env.SliceDel() {
				return false
			}
		} else if among_var == 2 {
			if !env.SliceDel() {
				return false
			}
		}
		break lab0
	}
	return true
}

func r_reflexive(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_3, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_verb(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_4, context)
	if among_var == 0 {
		return false
	}
	env.Bra = env.Cursor
	if among_var == 1 {
	lab0:
		for {
			var v_1 = env.Limit - env.Cursor
		lab1:
			for {
				if !env.EqSB("\u0430") {
					break lab1
				}
				break lab0
			}
			env.Cursor = env.Limit - v_1
			if !env.EqSB("\u044F") {
				return false
			}
			break lab0
		}
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !env.SliceDel() {
			return false
		}
	}
	return true
}

func r_noun(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_5, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_derivational(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_6, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !r_R2(env, context) {
		return false
	}
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_tidy_up(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_7, context)
	if among_var == 0 {
		return false
	}
	env.Bra = env.Cursor
	if among_var == 1 {
		if !env.SliceDel() {
			return false
		}
		env.Ket = env.Cursor
		if !env.EqSB("\u043D") {
			return false
		}
		env.Bra = env.Cursor
		if !env.EqSB("\u043D") {
			return false
		}
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !env.EqSB("\u043D") {
			return false
		}
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 3 {
		if !env.SliceDel() {
			return false
		}
	}
	return true
}

func Stem(env *snowballRuntime.Env) bool {
	var context = &Context{
		i_p2: 0,
		i_pV: 0,
	}
	_ = context
	var v_1 = env.Cursor
lab0:
	for {
	replab1:
		for {
			var v_2 = env.Cursor
		lab2:
			for _ = range [2]struct{}{} {
			golab3:
				for {
					var v_3 = env.Cursor
				lab4:
					for {
						env.Bra = env.Cursor
						if !env.EqS("\u0451") {
							break lab4
						}
						env.Ket = env.Cursor
						env.Cursor = v_3
						break golab3
					}
					env.Cursor = v_3
					if env.Cursor >= env.Limit {
						break lab2
					}
					env.NextChar()
				}
				if !env.SliceFrom("\u0435") {
					return false
				}
				continue replab1
			}
			env.Cursor = v_2
			break replab1
		}
		break lab0
	}
	env.Cursor = v_1
	r_mark_regions(env, context)
	env.LimitBackward = env.Cursor
	env.Cursor = env.Limit
	if env.Cursor < context.i_pV {
		return false
	}
	var v_6 = env.LimitBackward
	env.LimitBackward = context.i_pV
	var v_7 = env.Limit - env.Cursor
lab5:
	for {
	lab6:
		for {
			var v_8 = env.Limit - env.Cursor
		lab7:
			for {
				if !r_perfective_gerund(env, context) {
					break lab7
				}
				break lab6
			}
			env.Cursor = env.Limit - v_8
			var v_9 = env.Limit - env.Cursor
		lab8:
			for {
				if !r_reflexive(env, context) {
					env.Cursor = env.Limit - v_9
					break lab8
				}
				break lab8
			}
		lab9:
			for {
				var v_10 = env.Limit - env.Cursor
			lab10:
				for {
					if !r_adjectival(env, context) {
						break lab10
					}
					break lab9
				}
				env.Cursor = env.Limit - v_10
			lab11:
				for {
					if !r_verb(env, context) {
						break lab11
					}
					break lab9
				}
				env.Cursor = env.Limit - v_10
				if !r_noun(env, context) {
					break lab5
				}
				break lab9
			}
			break lab6
		}
		break lab5
	}
	env.Cursor = env.Limit - v_7
	var v_11 = env.Limit - env.Cursor
lab12:
	for {
		env.Ket = env.Cursor
		if !env.EqSB("\u0438") {
			env.Cursor = env.Limit - v_11
			break lab12
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
		break lab12
	}
	var v_12 = env.Limit - env.Cursor
	r_derivational(env, context)
	env.Cursor = env.Limit - v_12
	var v_13 = env.Limit - env.Cursor
	r_tidy_up(env, context)
	env.Cursor = env.Limit - v_13
	env.LimitBackward = v_6
	env.Cursor = env.LimitBackward
	return true
}
